### ISSUE TITLE
What flex section(s) are needed to create the IB Flex Query Report?

### ISSUE THREAD

**Issue by rproko01** [wesm/ib-flex-analyzer#1]
For me, when I go to IB Reports/Activty Flex Queries and create/edit a new flex query report, I have a choice of about 20 styles of reports such as "Change in NAV",  "Cash Report", "Trades", "Transaction Fees".  Each of these has perhaps 20 columns that can then be add or selected.  The README.MD says create a report with all fields, but from which section?  I created an "all fields" xml file for "Trades" but get the following error:

> python
Python 2.7.10 (default, Nov  7 2015, 11:34:05) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

>>> from ibflex.statement import FlexStatement
>>> statement=FlexStatement("../xml/TradesReport.xm")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ibflex/statement.py", line 13, in __init__
    stmt = self.get_lxml_root()
  File "ibflex/statement.py", line 52, in get_lxml_root
    tree = lxml_objectify.parse(open(self.path, 'rb'))
IOError: [Errno 2] No such file or directory: '../xml/TradesReport.xm'
>>> statement=FlexStatement("../xml/TradesReport.xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ibflex/statement.py", line 15, in __init__
    self.perf = clean_perf(stmt)
  File "ibflex/statement.py", line 58, in clean_perf
    summary = statement.MTDYTDPerformanceSummary
  File "src/lxml/lxml.objectify.pyx", line 229, in lxml.objectify.ObjectifiedElement.__getattr__ (src/lxml/lxml.objectify.c:4146)
  File "src/lxml/lxml.objectify.pyx", line 450, in lxml.objectify._lookupChildOrRaise (src/lxml/lxml.objectify.c:7030)
AttributeError: no such child: MTDYTDPerformanceSummary
>>>

**Comment by wesm** [comment]
You have to select the last business day of a month for it to output the MTD/YTD summary. For some reason

**Comment by wesm** [comment]
let me know if you weren't successful!
